### ISSUE TITLE
Consolidated getting started instructions

### ISSUE THREAD

**Issue by lukechurch** [lukechurch/iclc2016#4]
We needed a single consolidated 'getting started' page, describing:
- Everything that participants need to install (dart, node, etc.)
- How to configure the subcomponents (pub get, npm install, etc.)
- How to start the various components
- How to run the end to end test

We might consider writing a shell script to do most of this

**Comment by marianamarasoiu** [comment]
Added in commit c220742c0ec1eefa1d003d9ff4bece21f343f7d4

**Comment by lukechurch** [comment]
Thanks
